include:
  - component: $CI_SERVER_FQDN/dsi/plateforme/usine-logicielle/usilo-ci-cd-catalog/docker/gitlab-ci-docker@v1.1.4
    inputs:
      docker_build_context: "${CI_PROJECT_DIR}/"
      dockerfile: "deploy/Dockerfile"
      docker_registry_host: "artifactory.prusilo.interne.cloud.sacem.fr"
      docker_registry_username: "$USILO_USILO_ARTEFACT_REPOSITORY_USERNAME"
      docker_registry_password: "$USILO_USILO_ARTEFACT_REPOSITORY_PASSWORD"
      docker_build_image: "artifactory.prusilo.interne.cloud.sacem.fr/oci/executor:v0.0.1-debug"

default:
  variables:
    KANIKO_VERSION: v1.25.16
  tags:
    - onprem

stages:
  - lint
  - check
  - build
  - publish

.image-matrix: &image-matrix
  - VARIANT: warmer
    TARGET: kaniko-warmer
    IMAGE_REPO: artifactory.prusilo.interne.cloud.sacem.fr/dsi-train-plt-usine-logicielle-oci-sandbox/warmer
    PUBLISH_REPO: artifactory.prusilo.interne.cloud.sacem.fr/dsi-train-plt-usine-logicielle-oci/warmer
    IMAGE_TAG: "$KANIKO_VERSION"
  - VARIANT: executor
    TARGET: kaniko-executor
    IMAGE_REPO: artifactory.prusilo.interne.cloud.sacem.fr/dsi-train-plt-usine-logicielle-oci-sandbox/executor
    PUBLISH_REPO: artifactory.prusilo.interne.cloud.sacem.fr/dsi-train-plt-usine-logicielle-oci/executor
    IMAGE_TAG: "$KANIKO_VERSION"
  - VARIANT: debug
    TARGET: kaniko-debug
    IMAGE_REPO: artifactory.prusilo.interne.cloud.sacem.fr/dsi-train-plt-usine-logicielle-oci-sandbox/executor
    PUBLISH_REPO: artifactory.prusilo.interne.cloud.sacem.fr/dsi-train-plt-usine-logicielle-oci/executor
    IMAGE_TAG: "${KANIKO_VERSION}-debug"
  - VARIANT: slim
    TARGET: kaniko-slim
    IMAGE_REPO: artifactory.prusilo.interne.cloud.sacem.fr/dsi-train-plt-usine-logicielle-oci-sandbox/executor
    PUBLISH_REPO: artifactory.prusilo.interne.cloud.sacem.fr/dsi-train-plt-usine-logicielle-oci/executor
    IMAGE_TAG: "${KANIKO_VERSION}-slim"

lint-dockerfile:
  extends: .docker-hadolint
  allow_failure: true

check-snapshot:
  extends: .skopeo-inspect
  parallel:
    matrix: *image-matrix
  variables:
    DOCKER_BUILD_IMAGE_SNAPSHOT: "${IMAGE_REPO}:${IMAGE_TAG}"

build-image:
  extends: .docker-build
  parallel:
    matrix: *image-matrix
  variables:
    DOCKER_BUILD_IMAGE_SNAPSHOT: "${IMAGE_REPO}:${IMAGE_TAG}"
    DOCKER_BUILD_OPTIONS: "--target=${TARGET} --compressed-caching=false --snapshot-mode=redo"
  needs:
    - job: check-snapshot
      parallel:
        matrix: *image-matrix
      artifacts: true

publish-image:
  extends: .skopeo-copy
  parallel:
    matrix: *image-matrix
  variables:
    DOCKER_SRC_IMAGE: "${IMAGE_REPO}:${IMAGE_TAG}"
    DOCKER_DEST_IMAGE: "${PUBLISH_REPO}:${IMAGE_TAG}"
  needs:
    - job: build-image
      parallel:
        matrix: *image-matrix