include:
  - component: $CI_SERVER_FQDN/dsi/plateforme/usine-logicielle/usilo-ci-cd-catalog/docker/gitlab-ci-docker@v1.1.4
    inputs:
      docker_build_context: "${CI_PROJECT_DIR}/"
      dockerfile: "deploy/Dockerfile"
      docker_registry_host: "artifactory.prusilo.interne.cloud.sacem.fr"
      docker_registry_username: "$USILO_USILO_ARTEFACT_REPOSITORY_USERNAME"
      docker_registry_password: "$USILO_USILO_ARTEFACT_REPOSITORY_PASSWORD"
      # temporary unique test tag; pipeline run will substitute CI_PIPELINE_ID
      docker_build_image: "${OCI_REGISTRY_HOST}/${OCI_SANDBOX_BASE}/executor-debug-builder-test:${CI_PIPELINE_ID:-manual}"

variables:
  OCI_REGISTRY_HOST: artifactory.prusilo.interne.cloud.sacem.fr
  OCI_SANDBOX_BASE: dsi-train-plt-usine-logicielle-oci-sandbox

stages:
  - debug

inspect-builder-stage:
  extends: .docker-build
  stage: debug
  variables:
    # force building the 'builder' stage only
    DOCKER_BUILD_OPTIONS: "--target=builder --compressed-caching=false --snapshot-mode=redo"
    # push to a unique test tag so we don't overwrite anything important
    DOCKER_BUILD_IMAGE_SNAPSHOT: "${OCI_REGISTRY_HOST}/${OCI_SANDBOX_BASE}/executor-debug-builder-test:${CI_PIPELINE_ID:-manual}"
  script:
    - echo "This job builds the 'builder' stage and pushes a temporary image for inspection - ${DOCKER_BUILD_IMAGE_SNAPSHOT}"
  when: manual
